services:
  - type: web
    name: discord-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DISCORD_TOKEN
        value: ${DISCORD_TOKEN}
      - key: PORT
        value: "3000"
      - key: MONGODB_URI
        value: ${MONGODB_URI} # Tambahkan variabel lingkungan untuk MongoDB
        
